replicaCount: 1
nodeSelector: {}
image:
  repository: jenkins/jenkins
  pullPolicy: IfNotPresent
  tag: lts-jdk17
serviceAccount:
  create: false
ingress:
  enabled: true
  annotations: {}
  hosts:
  - host: jenkins.renlm.cn
    paths:
    - path: /
      pathType: Prefix
  tls:
  - secretName: renlm.secret
    hosts:
    - jenkins.renlm.cn
service:
  type: ClusterIP
  port: 80
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80