nodeSelector: {}
image:
  repository: jenkins/jenkins
  pullPolicy: IfNotPresent
  tag: lts-jdk17
serviceAccount:
  create: false
ingress:
  enabled: true
  annotations: {}
  hosts:
  - host: jenkins.renlm.cn
    paths:
    - path: /
      pathType: Prefix
  tls:
  - secretName: renlm.secret
    hosts:
    - jenkins.renlm.cn
service:
  type: ClusterIP
  port: 80