env: dev
replicaCount: 1
nodeSelector: {}
image:
  repository: registry.cn-hangzhou.aliyuncs.com/rlm/mygraph
  pullPolicy: Always
  tag: latest
serviceAccount:
  create: true
  annotations: {}
  name: mygraph-service-account
ingress:
  enabled: true
  annotations: {}
  hosts:
  - host: mygraph.renlm.cn
    paths:
    - path: /
      pathType: Prefix
  tls:
  - secretName: renlm.secret
    hosts:
    - mygraph.renlm.cn
service:
  type: ClusterIP
  port: 8080
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
# 子Chart配置
prometheus:
  enabled: true
  port: spring-cloud
  selector:
  - name: spring-cloud
    value: enable
redis:
  enabled: true
  requirepass: PWD@20xx$
rabbitmq:
  enabled: true
  defaultVhost: /mygraph
  defaultUser: mygraph
  defaultPass: PWD@20xx$
mysql:
  enabled: true
  database: mygraph
  user: mygraph
  password: PWD@20xx$