version: 1.0.1
env: dev
initDb: true
host: mygraph.renlm.cn
replicaCount: 1
nodeSelector: {}
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
tolerations: []
affinity: {}
imagePullSecrets: []
image:
  repository: registry.cn-hangzhou.aliyuncs.com/rlm/mygraph
  pullPolicy: Always
  tag: latest
serviceAccount:
  create: true
  annotations: {}
  name: mygraph-sa
ingress:
  enabled: false
service:
  type: ClusterIP
  port: 8080
actuator:
  port: 9000
  portName: tcp-actuator
  health:
    liveness:
      initialDelaySeconds: 3
      periodSeconds: 10
      successThreshold: 1
      failureThreshold: 20
      timeoutSeconds: 1
    readiness:
      initialDelaySeconds: 3
      periodSeconds: 10
      successThreshold: 1
      failureThreshold: 20
      timeoutSeconds: 1
resources:
  limits:
    memory: 4Gi
    cpu: 2
  requests:
    memory: 500Mi
    cpu: 200m
autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80