mygraph:
  image: registry.cn-hangzhou.aliyuncs.com/rlm/mygraph
  host: mygraph.renlm.cn
  tlsSecretName: renlm.secret
  imagePullSecrets: aliyun.secret
  serverPort: 8080
  replicaCount: 1
  serviceAccount:
    create: true
    annotations: {}
    name: mygraph-service-account
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80
prometheus:
  enabled: false
  port: 9000
  portName: prometheus