apiVersion: v2
appVersion: 1.0.1
name: devrke2-ingress-nginx
version: 4.10.0
description: 开启ssl透传
keywords:
- https://kubernetes.github.io/ingress-nginx/deploy/
dependencies:
- name: ingress-nginx
  repository: https://renlm.gitee.io/helm/repo
  version: 4.10.0