ingress-nginx:
  controller:
    kind: DaemonSet
    containerName: devrke2-ingress-nginx-controller
    extraArgs:
      enable-ssl-passthrough: false
    admissionWebhooks:
      patch:
        enabled: true
        image:
          registry: registry.cn-hangzhou.aliyuncs.com
          image: rlm/ingress-nginx-kube-webhook-certgen
          tag: v1.4.0
          pullPolicy: IfNotPresent
    image:
      registry: registry.cn-hangzhou.aliyuncs.com
      image: rlm/ingress-nginx-controller
      tag: v1.4.0
      pullPolicy: IfNotPresent
    ingressClass: nginx-devrke2
    ingressClassResource:
      name: nginx-devrke2