ingress-nginx:
  global:
    systemDefaultRegistry: ''
    clusterCIDR: 10.42.0.0/16
    clusterCIDRv4: 10.42.0.0/16
    clusterDNS: 10.43.0.10
    clusterDomain: cluster.local
    rke2DataDir: /var/lib/rancher/rke2
    serviceCIDR: 10.43.0.0/166
  controller:
    kind: DaemonSet
    containerName: devrke2-ingress-nginx-controller
    ingressClass: nginx-devrke2
    ingressClassResource:
      name: nginx-devrke2
    extraArgs:
      enable-ssl-passthrough: false
    image:
      registry: registry.cn-hangzhou.aliyuncs.com
      image: rlm/ingress-nginx-controller
      tag: v1.10.0
      digest: sha256:dc6951b9413a7173b7474ecc4fdc6adf930058f4021a10c5ad802afab6382a8a
      pullPolicy: IfNotPresent
    admissionWebhooks:
      patch:
        enabled: true
        image:
          registry: registry.cn-hangzhou.aliyuncs.com
          image: rlm/ingress-nginx-kube-webhook-certgen
          tag: v1.4.0
          digest: sha256:cf6d2b44254ec4ae74216084c6761601f02e712c30a8061155fd6cb2c5fdb126
          pullPolicy: IfNotPresent