ingress-nginx:
  controller:
    containerName: devrke2-ingress-nginx-controller
    ingressClass: nginx-devrke2
    ingressClassResource:
      name: nginx-devrke2
    extraArgs:
      enable-ssl-passthrough: false