apiVersion: v1
entries:
  ingress-nginx:
  - annotations:
      artifacthub.io/changes: '- "Update Ingress-Nginx version controller-v1.10.0"'
      artifacthub.io/prerelease: "false"
    apiVersion: v2
    appVersion: 1.10.0
    created: "2024-03-08T13:36:53.451800852+08:00"
    description: Ingress controller for Kubernetes using NGINX as a reverse proxy
      and load balancer
    digest: 74f6590786bee20295bbe76f914514d9a111d7e9317acf13d26de482ae8abc1a
    home: https://github.com/kubernetes/ingress-nginx
    icon: https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Nginx_logo.svg/500px-Nginx_logo.svg.png
    keywords:
    - ingress
    - nginx
    kubeVersion: '>=1.20.0-0'
    maintainers:
    - name: rikatz
    - name: strongjz
    - name: tao12345666333
    name: ingress-nginx
    sources:
    - https://github.com/kubernetes/ingress-nginx
    urls:
    - https://renlm.gitee.io/helm/repo/ingress-nginx-4.10.0.tgz
    version: 4.10.0
  ingress-nginx-ssl:
  - apiVersion: v2
    appVersion: 1.0.1
    created: "2024-03-08T20:09:32.020843498+08:00"
    dependencies:
    - condition: frr-k8s.enabled
      name: frr-k8s
      repository: https://metallb.github.io/frr-k8s
      version: 0.0.8
    - condition: ingress-nginx.enabled
      name: ingress-nginx
      repository: https://renlm.gitee.io/helm/repo
      version: 4.10.0
    description: 开启ssl透传
    digest: 3509977cd92cdc71846dd26e815199249e7dffe8d62bc37db4a4a9541feeee88
    keywords:
    - https://kubernetes.github.io/ingress-nginx/deploy/
    name: ingress-nginx-ssl
    urls:
    - https://renlm.gitee.io/helm/repo/ingress-nginx-ssl-4.10.0.tgz
    version: 4.10.0
  jenkins:
  - apiVersion: v2
    appVersion: 1.0.1
    created: "2024-03-08T13:36:53.462451758+08:00"
    digest: f098748871e1f3b9fa2e1266435d445ade588d770407636b6d4a38b19f1a6077
    name: jenkins
    urls:
    - https://renlm.gitee.io/helm/repo/jenkins-0.1.0.tgz
    version: 0.1.0
  mysql:
  - apiVersion: v2
    appVersion: 1.0.1
    created: "2024-03-08T13:36:53.46295166+08:00"
    digest: 432b3551ab6773ca65591935c60c20129eaf635366885946abc38889573825ab
    name: mysql
    urls:
    - https://renlm.gitee.io/helm/repo/mysql-0.1.0.tgz
    version: 0.1.0
  prometheus:
  - apiVersion: v2
    appVersion: 1.0.1
    created: "2024-03-08T13:36:53.463263668+08:00"
    digest: 9f9e6b5910c41ee1f4c6fc195e636d5b858521b268c18619ae8c2c69b9c0334f
    name: prometheus
    urls:
    - https://renlm.gitee.io/helm/repo/prometheus-0.1.0.tgz
    version: 0.1.0
  rabbitmq:
  - apiVersion: v2
    appVersion: 1.0.1
    created: "2024-03-08T13:36:53.464527865+08:00"
    digest: 286ae036608d4f071cb3215070109ad3365c5229cd8f7153f7ebc44d56049ee8
    name: rabbitmq
    urls:
    - https://renlm.gitee.io/helm/repo/rabbitmq-0.1.0.tgz
    version: 0.1.0
  redis:
  - apiVersion: v2
    appVersion: 1.0.1
    created: "2024-03-08T13:36:53.464906983+08:00"
    digest: 62211de6e7415e13691323eb1e1612708596f53980a5f33c8d4955da502c51a7
    name: redis
    urls:
    - https://renlm.gitee.io/helm/repo/redis-0.1.0.tgz
    version: 0.1.0
  mygraph:
  - apiVersion: v2
    appVersion: 1.0.1
    created: "2024-03-08T20:14:30.03056715+08:00"
    dependencies:
    - condition: prometheus.enabled
      name: prometheus
      repository: https://renlm.gitee.io/helm/repo
      version: 0.1.0
    - condition: redis.enabled
      name: redis
      repository: https://renlm.gitee.io/helm/repo
      version: 0.1.0
    - condition: mysql.enabled
      name: mysql
      repository: https://renlm.gitee.io/helm/repo
      version: 0.1.0
    - condition: rabbitmq.enabled
      name: rabbitmq
      repository: https://renlm.gitee.io/helm/repo
      version: 0.1.0
    - condition: jenkins.enabled
      name: jenkins
      repository: https://renlm.gitee.io/helm/repo
      version: 0.1.0
    digest: f0ce1e22675e5f622ea2b11a61536f111480296c83c2ff1125a6c27a897a3086
    name: mygraph
    urls:
    - https://renlm.gitee.io/helm/repo/mygraph-1.0.1.tgz
    version: 1.0.1
generated: "2024-03-08T13:36:53.446143534+08:00"
