apiVersion: v1
entries:
  ingress-nginx:
  - annotations:
      artifacthub.io/changes: '- "Update Ingress-Nginx version controller-v1.10.0"'
      artifacthub.io/prerelease: "false"
    apiVersion: v2
    appVersion: 1.10.0
    created: "2024-03-05T12:29:06.560463012+08:00"
    description: Ingress controller for Kubernetes using NGINX as a reverse proxy
      and load balancer
    digest: 74f6590786bee20295bbe76f914514d9a111d7e9317acf13d26de482ae8abc1a
    home: https://github.com/kubernetes/ingress-nginx
    icon: https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Nginx_logo.svg/500px-Nginx_logo.svg.png
    keywords:
    - ingress
    - nginx
    kubeVersion: '>=1.20.0-0'
    maintainers:
    - name: rikatz
    - name: strongjz
    - name: tao12345666333
    name: ingress-nginx
    sources:
    - https://github.com/kubernetes/ingress-nginx
    urls:
    - https://renlm.gitee.io/helm/repo/ingress-nginx-4.10.0.tgz
    version: 4.10.0
  jenkins:
  - apiVersion: v2
    appVersion: 1.0.1
    created: "2024-03-05T12:29:06.560859243+08:00"
    digest: 0e04ce8b254aba2a43814fafeae8f4801492b5815e75844bf6c7cb47eac60ffb
    name: jenkins
    urls:
    - https://renlm.gitee.io/helm/repo/jenkins-0.1.0.tgz
    version: 0.1.0
  mysql:
  - apiVersion: v2
    appVersion: 1.0.1
    created: "2024-03-05T12:29:06.561141073+08:00"
    digest: 0690f54fc9ca86b2afa9ec2906d32b7759fe252664c894608c3d6c4d5e8ac926
    name: mysql
    urls:
    - https://renlm.gitee.io/helm/repo/mysql-0.1.0.tgz
    version: 0.1.0
  prometheus:
  - apiVersion: v2
    appVersion: 1.0.1
    created: "2024-03-05T12:29:06.561439135+08:00"
    digest: 74284e697f24734ed9fb7940e0074e672d1332104eb1091b399ae19076b2da01
    name: prometheus
    urls:
    - https://renlm.gitee.io/helm/repo/prometheus-0.1.0.tgz
    version: 0.1.0
  rabbitmq:
  - apiVersion: v2
    appVersion: 1.0.1
    created: "2024-03-05T12:29:06.561814386+08:00"
    digest: 80d03a0cec151b4c9ee6ed027d01f55f104de0e13d7013eb51d04825114ed6f9
    name: rabbitmq
    urls:
    - https://renlm.gitee.io/helm/repo/rabbitmq-0.1.0.tgz
    version: 0.1.0
  redis:
  - apiVersion: v2
    appVersion: 1.0.1
    created: "2024-03-05T12:29:06.562087329+08:00"
    digest: 8f59e0e75baf1cb326c615fc50b6eeeaf9041be9b9092ac58bd986f97193e9e3
    name: redis
    urls:
    - https://renlm.gitee.io/helm/repo/redis-0.1.0.tgz
    version: 0.1.0
  devrke2-ingress-nginx:
  - apiVersion: v2
    appVersion: 1.0.1
    created: "2024-03-05T15:26:16.734439509+08:00"
    dependencies:
    - name: ingress-nginx
      repository: https://renlm.gitee.io/helm/repo
      version: 4.10.0
    description: 开启ssl透传
    digest: eff387767db14b7528036b80b822c9ce9106dd12703ff6974a63395677568aa5
    keywords:
    - https://kubernetes.github.io/ingress-nginx/deploy/
    name: devrke2-ingress-nginx
    urls:
    - https://renlm.gitee.io/helm/repo/devrke2-ingress-nginx-4.10.0.tgz
    version: 4.10.0
  mygraph:
  - apiVersion: v2
    appVersion: 1.0.1
    created: "2024-03-05T12:35:52.808506254+08:00"
    dependencies:
    - condition: prometheus.enabled
      name: prometheus
      repository: https://renlm.gitee.io/helm/repo
      version: 0.1.0
    - condition: redis.enabled
      name: redis
      repository: https://renlm.gitee.io/helm/repo
      version: 0.1.0
    - condition: mysql.enabled
      name: mysql
      repository: https://renlm.gitee.io/helm/repo
      version: 0.1.0
    - condition: rabbitmq.enabled
      name: rabbitmq
      repository: https://renlm.gitee.io/helm/repo
      version: 0.1.0
    - condition: jenkins.enabled
      name: jenkins
      repository: https://renlm.gitee.io/helm/repo
      version: 0.1.0
    digest: 5c5b441a3f2f53b856fcacd0805f6ef353c50dd53b11e3abb78b525c750442df
    name: mygraph
    urls:
    - https://renlm.gitee.io/helm/repo/mygraph-0.1.0.tgz
    version: 0.1.0
generated: "2024-03-05T12:29:06.553649918+08:00"
