apiVersion: v1
entries:
  jenkins:
  - apiVersion: v2
    appVersion: 1.0.1
    created: "2024-03-02T14:53:41.073090023+08:00"
    digest: a5ae7b93d570c3f71477856d8791615e6b1befe91388200d30c7aadc0c87e397
    name: jenkins
    urls:
    - https://renlm.gitee.io/helm/repo/jenkins-0.1.0.tgz
    version: 0.1.0
  mysql:
  - apiVersion: v2
    appVersion: 1.0.1
    created: "2024-03-02T14:53:41.07377678+08:00"
    digest: d22ce1d3feb5478ccbaf3dad09ced36af0e19ded6e3ebf34db3255d5ee8bab29
    name: mysql
    urls:
    - https://renlm.gitee.io/helm/repo/mysql-0.1.0.tgz
    version: 0.1.0
  prometheus:
  - apiVersion: v2
    appVersion: 1.0.1
    created: "2024-03-02T14:53:41.074233149+08:00"
    digest: 8beb5caa2d476a8700ec42bda37494e7faf53661346cf06e013a5ebe7434fc33
    name: prometheus
    urls:
    - https://renlm.gitee.io/helm/repo/prometheus-0.1.0.tgz
    version: 0.1.0
  rabbitmq:
  - apiVersion: v2
    appVersion: 1.0.1
    created: "2024-03-02T14:53:41.074814412+08:00"
    digest: f24e2621a0cd407c3c3f406eb8621be2ae03652271066ccfaff52351e45a39fc
    name: rabbitmq
    urls:
    - https://renlm.gitee.io/helm/repo/rabbitmq-0.1.0.tgz
    version: 0.1.0
  redis:
  - apiVersion: v2
    appVersion: 1.0.1
    created: "2024-03-02T14:53:41.07528359+08:00"
    digest: ff4d4a8db7239c1f31608501a08e93410ee1658a146773b29d827301dbe14c44
    name: redis
    urls:
    - https://renlm.gitee.io/helm/repo/redis-0.1.0.tgz
    version: 0.1.0
  mygraph:
  - apiVersion: v2
    appVersion: 1.0.1
    created: "2024-03-02T14:58:08.932837616+08:00"
    dependencies:
    - condition: prometheus.enabled
      name: prometheus
      repository: https://renlm.gitee.io/helm/repo
      version: 0.1.0
    - condition: redis.enabled
      name: redis
      repository: https://renlm.gitee.io/helm/repo
      version: 0.1.0
    - condition: mysql.enabled
      name: mysql
      repository: https://renlm.gitee.io/helm/repo
      version: 0.1.0
    - condition: rabbitmq.enabled
      name: rabbitmq
      repository: https://renlm.gitee.io/helm/repo
      version: 0.1.0
    - condition: jenkins.enabled
      name: jenkins
      repository: https://renlm.gitee.io/helm/repo
      version: 0.1.0
    digest: e98067593d202e3b5a8da07407af640b019d5e6149c3428dbc6587e86bfb8c25
    name: mygraph
    urls:
    - https://renlm.gitee.io/helm/repo/mygraph-0.1.0.tgz
    version: 0.1.0
generated: "2024-03-02T14:53:41.069594286+08:00"
