apiVersion: v1
entries:
  mysql:
  - apiVersion: v2
    appVersion: 1.0.1
    created: "2024-02-29T14:31:40.937096819+08:00"
    digest: 6dca2a180e867b27a6cccea477582a657cdf99184323c6aeebe02a883ea7a7c4
    name: mysql
    urls:
    - https://renlm.gitee.io/helm/repo/mysql-0.1.0.tgz
    version: 0.1.0
  prometheus:
  - apiVersion: v2
    appVersion: 1.0.1
    created: "2024-02-29T14:31:40.937445066+08:00"
    digest: 4c81138b90db27f282785c71b97e9ae38c5614425254bb6bb4671325024c3fe8
    name: prometheus
    urls:
    - https://renlm.gitee.io/helm/repo/prometheus-0.1.0.tgz
    version: 0.1.0
  rabbitmq:
  - apiVersion: v2
    appVersion: 1.0.1
    created: "2024-02-29T14:31:40.938071949+08:00"
    digest: 6d7a20e78ebb3914bc9dd0c645a8d0e40e152d2f527d4faa6ce84f6bc978e2fe
    name: rabbitmq
    urls:
    - https://renlm.gitee.io/helm/repo/rabbitmq-0.1.0.tgz
    version: 0.1.0
  redis:
  - apiVersion: v2
    appVersion: 1.0.1
    created: "2024-02-29T14:31:40.938462367+08:00"
    digest: fe24f6217136e670ad07c3bcb32b24228aa10f971ab7cc76da464335ba19e287
    name: redis
    urls:
    - https://renlm.gitee.io/helm/repo/redis-0.1.0.tgz
    version: 0.1.0
  mygraph:
  - apiVersion: v2
    appVersion: 1.0.1
    created: "2024-02-29T14:36:34.042270849+08:00"
    dependencies:
    - condition: prometheus.enabled
      name: prometheus
      repository: https://renlm.gitee.io/helm/repo
      version: 0.1.0
    - condition: redis.enabled
      name: redis
      repository: https://renlm.gitee.io/helm/repo
      version: 0.1.0
    - condition: rabbitmq.enabled
      name: rabbitmq
      repository: https://renlm.gitee.io/helm/repo
      version: 0.1.0
    - condition: mysql.enabled
      name: mysql
      repository: https://renlm.gitee.io/helm/repo
      version: 0.1.0
    digest: fe58a4d9d56c1a3c5b6fd31e82f43788cbfdf95ed80f01479928684dc7f1878b
    name: mygraph
    urls:
    - https://renlm.gitee.io/helm/repo/mygraph-0.1.0.tgz
    version: 0.1.0
generated: "2024-02-29T14:31:40.936411283+08:00"
