apiVersion: v1
entries:
  frr-k8s:
  - apiVersion: v2
    appVersion: v0.0.8
    created: "2024-03-09T14:46:17.416170664+08:00"
    dependencies:
    - condition: crds.enabled
      name: crds
      repository: ""
      version: 0.0.8
    description: A cloud native wrapper of FRR
    digest: 407c41edb20ea223dc8b05e5e712f4a1fa4e7578ba1e1d43411146e2d0e5790c
    home: https://metallb.universe.tf
    icon: https://metallb.universe.tf/images/logo/metallb-white.png
    kubeVersion: '>= 1.19.0-0'
    name: frr-k8s
    sources:
    - https://github.com/metallb/frr-k8s
    type: application
    urls:
    - https://renlm.gitee.io/helm/repo/frr-k8s-0.0.8.tgz
    version: 0.0.8
  ingress-nginx:
  - annotations:
      artifacthub.io/changes: '- "Update Ingress-Nginx version controller-v1.10.0"'
      artifacthub.io/prerelease: "false"
    apiVersion: v2
    appVersion: 1.10.0
    created: "2024-03-09T14:46:17.42246312+08:00"
    description: Ingress controller for Kubernetes using NGINX as a reverse proxy
      and load balancer
    digest: 74f6590786bee20295bbe76f914514d9a111d7e9317acf13d26de482ae8abc1a
    home: https://github.com/kubernetes/ingress-nginx
    icon: https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Nginx_logo.svg/500px-Nginx_logo.svg.png
    keywords:
    - ingress
    - nginx
    kubeVersion: '>=1.20.0-0'
    maintainers:
    - name: rikatz
    - name: strongjz
    - name: tao12345666333
    name: ingress-nginx
    sources:
    - https://github.com/kubernetes/ingress-nginx
    urls:
    - https://renlm.gitee.io/helm/repo/ingress-nginx-4.10.0.tgz
    version: 4.10.0
  jenkins:
  - apiVersion: v2
    appVersion: 1.0.1
    created: "2024-03-09T14:46:17.424013229+08:00"
    digest: e2db351665e935c8298e6ad43e93571b2c05654144f1bec2059578e363844d7a
    name: jenkins
    urls:
    - https://renlm.gitee.io/helm/repo/jenkins-0.1.0.tgz
    version: 0.1.0
  mysql:
  - apiVersion: v2
    appVersion: 1.0.1
    created: "2024-03-09T14:46:17.424752033+08:00"
    digest: 8534386301c4dc2d187c2dcd810df8f9ba05e9da983c538de82b744b560d408d
    name: mysql
    urls:
    - https://renlm.gitee.io/helm/repo/mysql-0.1.0.tgz
    version: 0.1.0
  prometheus:
  - apiVersion: v2
    appVersion: 1.0.1
    created: "2024-03-09T14:46:17.425466776+08:00"
    digest: e159516ee6524fa212a97662d0f4375f1e38862b8033f7030ee24204cde2eb06
    name: prometheus
    urls:
    - https://renlm.gitee.io/helm/repo/prometheus-0.1.0.tgz
    version: 0.1.0
  rabbitmq:
  - apiVersion: v2
    appVersion: 1.0.1
    created: "2024-03-09T14:46:17.426353308+08:00"
    digest: 5f21ff936c0ed042bc2b622c643b5442aebb1d870e611c9bbb463d66e54fd746
    name: rabbitmq
    urls:
    - https://renlm.gitee.io/helm/repo/rabbitmq-0.1.0.tgz
    version: 0.1.0
  redis:
  - apiVersion: v2
    appVersion: 1.0.1
    created: "2024-03-09T14:46:17.427026198+08:00"
    digest: 9c68d36cba0f5932ab66bc15298fe5b12a58989009cba05c9316bc144fa54986
    name: redis
    urls:
    - https://renlm.gitee.io/helm/repo/redis-0.1.0.tgz
    version: 0.1.0
generated: "2024-03-09T14:46:17.411846328+08:00"
