apiVersion: v1
entries:
  ingress-nginx:
  - annotations:
      artifacthub.io/changes: '- "Update Ingress-Nginx version controller-v1.10.0"'
      artifacthub.io/prerelease: "false"
    apiVersion: v2
    appVersion: 1.10.0
    created: "2024-03-09T17:19:44.937354137+08:00"
    description: Ingress controller for Kubernetes using NGINX as a reverse proxy
      and load balancer
    digest: 74f6590786bee20295bbe76f914514d9a111d7e9317acf13d26de482ae8abc1a
    home: https://github.com/kubernetes/ingress-nginx
    icon: https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Nginx_logo.svg/500px-Nginx_logo.svg.png
    keywords:
    - ingress
    - nginx
    kubeVersion: '>=1.20.0-0'
    maintainers:
    - name: rikatz
    - name: strongjz
    - name: tao12345666333
    name: ingress-nginx
    sources:
    - https://github.com/kubernetes/ingress-nginx
    urls:
    - https://renlm.gitee.io/helm/repo/ingress-nginx-4.10.0.tgz
    version: 4.10.0
  jenkins:
  - apiVersion: v2
    appVersion: 1.0.1
    created: "2024-03-09T17:19:44.94112655+08:00"
    digest: fdf6afbbf0f7b9f56f52519c9b010bce11d89056abffd7a245a14e27ef179dab
    name: jenkins
    urls:
    - https://renlm.gitee.io/helm/repo/jenkins-0.1.0.tgz
    version: 0.1.0
  mysql:
  - apiVersion: v2
    appVersion: 1.0.1
    created: "2024-03-09T17:19:44.942252049+08:00"
    digest: d6a452b97a6e8f26674eb3beb05a5bf007365bde78a0bdab67f315025de1302e
    name: mysql
    urls:
    - https://renlm.gitee.io/helm/repo/mysql-0.1.0.tgz
    version: 0.1.0
  prometheus:
  - apiVersion: v2
    appVersion: 1.0.1
    created: "2024-03-09T17:19:44.94940345+08:00"
    digest: 930c2ad332400ec17b648702e10f14af2b799f69a74ab1395b86990e9ab641cf
    name: prometheus
    urls:
    - https://renlm.gitee.io/helm/repo/prometheus-0.1.0.tgz
    version: 0.1.0
  rabbitmq:
  - apiVersion: v2
    appVersion: 1.0.1
    created: "2024-03-09T17:19:44.950235369+08:00"
    digest: 064a1d8d3fdc536acc9a5daf20b2989df2f5446106d60e1420df94d3486791cd
    name: rabbitmq
    urls:
    - https://renlm.gitee.io/helm/repo/rabbitmq-0.1.0.tgz
    version: 0.1.0
  redis:
  - apiVersion: v2
    appVersion: 1.0.1
    created: "2024-03-09T17:19:44.95086141+08:00"
    digest: 9a1ca2f50d84f3d8f6f76fb7589d7b52923f711b25685762266e4af9018d4e4d
    name: redis
    urls:
    - https://renlm.gitee.io/helm/repo/redis-0.1.0.tgz
    version: 0.1.0
generated: "2024-03-09T17:19:44.923288902+08:00"
