{{- if .Values.mygraph.serviceAccount.create -}}
apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: {{ include "mygraph.serviceAccountName" . }}
      labels:
        {{- include "mygraph.labels" . | nindent 4 }}
      {{- with .Values.mygraph.serviceAccount.annotations }}
      annotations:
        {{- toYaml . | nindent 4 }}
      {{- end }}
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: {{ include "mygraph.fullname" . }}-role-binding
      labels:
        {{- include "mygraph.labels" . | nindent 4 }}
    roleRef:
      kind: Role
      apiGroup: rbac.authorization.k8s.io
      name: {{ include "mygraph.fullname" . }}-role
    subjects:
      - kind: ServiceAccount
        name: {{ include "mygraph.serviceAccountName" . }}
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: Role
    metadata:
      name: {{ include "mygraph.fullname" . }}-role
    rules:
      - apiGroups: ["", "extensions", "apps"]
        resources: ["configmaps", "pods", "services", "endpoints", "secrets"]
        verbs: ["get", "list", "watch"]
{{- end }}