apiVersion: v1
kind: Service
metadata:
  name: {{ include "mygraph.fullname" . }}
  labels:
    {{- include "mygraph.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - name: http
      port: {{ .Values.mygraph.serverPort }}
      protocol: TCP
      targetPort: {{ .Values.mygraph.serverPort }}
    - name: {{ .Values.prometheus.portName }}
      port: {{ .Values.prometheus.port }}
      protocol: TCP
      targetPort: {{ .Values.prometheus.port }}
  selector:
    {{- include "mygraph.selectorLabels" . | nindent 4 }}