apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis.fullname" . }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: 6379
      targetPort: 6379
      nodePort: {{ .Values.redis.nodePort }}
  selector:
    {{- include "redis.selectorLabels" . | nindent 4 }}