apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "redis.fullname" . }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "redis.fullname" . }}
  replicas: 1
  selector:
    matchLabels:
      {{- include "redis.selectorLabels" . | nindent 6 }}
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        {{- include "redis.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image }}
          imagePullPolicy: IfNotPresent
          command: 
            - redis-server
            - /etc/redis/redis.conf
          env:
            - name: TZ
              value: Asia/Shanghai
          ports:
            - containerPort: 6379
              name: redis
          volumeMounts:
            - name: redis-conf
              mountPath: /etc/redis/redis.conf
              subPath: redis.conf
            - name: redis-lib
              mountPath: /var/lib/redis
      volumes:
        - name: redis-conf
          configMap:
            name: {{ include "redis.fullname" . }}-configmap
            items:
            - key: redis.conf
              path: redis.conf
        - name: redis-lib
          hostPath:
            path: /var/lib/redis