mini: true
database: dev
user: dev
password: PWD
nodeSelector: {}
image:
  repository: mysql
  pullPolicy: IfNotPresent
  tag: 8.0.31
serviceAccount:
  create: false
ingress:
  enabled: false
service:
  type: NodePort
  port: 3306
  nodePort: 30306