# https://istio.io/latest/zh/docs/setup/additional-setup/gateway/
# https://istio.io/latest/zh/docs/tasks/traffic-management/ingress/kubernetes-ingress/
apiVersion: v1
kind: List
items:
- apiVersion: networking.k8s.io/v1
  kind: IngressClass
  metadata:
    name: istio
  spec:
    controller: istio.io/ingress-controller
- apiVersion: cert-manager.io/v1
  kind: ClusterIssuer
  metadata:
    name: letsencrypt-issuer
    namespace: istio-system
  spec:
    acme:
      # The ACME server URL
      server: https://acme-v02.api.letsencrypt.org/directory
      # Email address used for ACME registration
      email: renlm@21cn.com
      # Name of a secret used to store the ACME account private key
      privateKeySecretRef:
        name: letsencrypt-issuer
      # Enable the HTTP-01 challenge provider
      solvers:
      # An empty 'selector' means that this solver matches all domains
      - selector: {}
        http01:
          ingress:
            # istio | nginx | traefik
            class: istio
- apiVersion: cert-manager.io/v1
  kind: Certificate
  metadata:
    name: renlm.cn
    namespace: istio-system
  spec:
    secretName: renlm.cn
    duration: 2160h
    renewBefore: 360h
    subject:
      organizations:
      - renlm.cn
    dnsNames:
    - renlm.cn
    - www.renlm.cn
    - rancher.renlm.cn
    - jenkins.renlm.cn
    - rabbitmq.renlm.cn
    - mygraph.renlm.cn
    issuerRef:
      name: letsencrypt-issuer
      kind: ClusterIssuer
- apiVersion: networking.istio.io/v1beta1
  kind: Gateway
  metadata:
    name: gateway
    namespace: istio-system
  spec:
    selector:
      istio: ingressgateway
    servers:
    - port:
        number: 80
        protocol: HTTP
        name: http
      hosts:
      - renlm.cn
      - www.renlm.cn
      - rancher.renlm.cn
      - jenkins.renlm.cn
      - rabbitmq.renlm.cn
      - mygraph.renlm.cn
    - port:
        number: 443
        protocol: HTTPS
        name: https
      hosts:
      - renlm.cn
      - www.renlm.cn
      - rancher.renlm.cn
      - jenkins.renlm.cn
      - rabbitmq.renlm.cn
      - mygraph.renlm.cn
      tls:
        mode: SIMPLE
        credentialName: renlm.cn
        minProtocolVersion: TLSV1_2
- apiVersion: networking.istio.io/v1beta1
  kind: VirtualService
  metadata:
    name: rancher
    namespace: istio-system
  spec:
    hosts:
    - rancher.renlm.cn
    gateways:
    - gateway
    http:
    - match:
      - port: 80
      - port: 443
      route:
      - weight: 100
        destination:
          host: rancher.cattle-system.svc.cluster.local
          port:
            number: 80