# https://istio.io/latest/zh/docs/setup/additional-setup/gateway/
# https://istio.io/latest/zh/docs/tasks/traffic-management/ingress/kubernetes-ingress/
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: ingress
spec:
  profile: empty
  components:
    ingressGateways:
    - name: istio-ingressgateway
      namespace: istio-ingress
      enabled: true
      label:
        istio: ingressgateway
  values:
    gateways:
      istio-ingressgateway:
        injectionTemplate: gateway