# https://istio.io/latest/zh/docs/setup/additional-setup/gateway/
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: ingress
spec:
  profile: empty
  meshConfig:
    defaultConfig:
      gatewayTopology:
        numTrustedProxies: 3
  components:
    ingressGateways:
    - name: istio-ingressgateway
      namespace: istio-ingress
      enabled: true
      label:
        istio: ingressgateway
  values:
    gateways:
      istio-ingressgateway:
        injectionTemplate: gateway