apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: Jaeger
  namespace: istio-system
spec:
  strategy: allInOne
  allInOne:
    options:
      log-level: info
      query:
        base-path: /jaeger
        service:
          name: tracing
      prometheus:
        server-url: http://rancher-monitoring-prometheus.cattle-monitoring-system.svc:9090
    metricsStorage:
      type: prometheus
  storage:
    options:
      memory:
        max-traces: 50000