apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: tracing
  namespace: istio-system
spec:
  strategy: allInOne
  allInOne:
    options:
      log-level: debug
      query:
        base-path: /jaeger
      prometheus:
        server-url: http://rancher-monitoring-prometheus.cattle-monitoring-system.svc:9090
        query:
          support-spanmetrics-connector: true
    metricsStorage:
      type: prometheus
  storage:
    options:
      memory:
        max-traces: 50000