apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: tracing
  namespace: observability
spec:
  strategy: production
  query:
    base-path: /jaeger
    metricsStorage:
      type: prometheus
      server-url: http://rancher-monitoring-prometheus.cattle-monitoring-system.svc:9090
  collector:
    maxReplicas: 2
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
  storage:
    options:
      memory:
        max-traces: 50000