# https://github.com/open-telemetry/opentelemetry-operator/tree/main/cmd/otel-allocator#prometheuscr-specifics
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: opentelemetry-targetallocator-sa
    namespace: otel-metrics
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    name: opentelemetry-targetallocator-cr
  rules:
  - apiGroups:
    - monitoring.coreos.com
    resources:
    - servicemonitors
    - podmonitors
    verbs:
    - "*"
  - apiGroups: [""]
    resources:
    - namespaces
    verbs: ["get", "list", "watch"]
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: opentelemetry-targetallocator-crb
    namespace: otel-metrics
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: opentelemetry-targetallocator-cr
  subjects:
    - kind: ServiceAccount
      name: opentelemetry-targetallocator-sa
      namespace: otel-metrics
- apiVersion: monitoring.coreos.com/v1
  kind: PodMonitor
  metadata:
    name: jaeger-component-monitor
    namespace: observability
    labels:
      monitoring: jaeger-components
  spec:
    podMetricsEndpoints:
    - interval: 15s
      path: /metrics
      port: admin-http
    namespaceSelector:
      matchNames:
      - istio-system
      - observability
    selector:
      matchExpressions:
      - key: app.kubernetes.io/managed-by
        operator: In
        values:
        - jaeger-operator
- apiVersion: opentelemetry.io/v1alpha1
  kind: OpenTelemetryCollector
  metadata:
    name: otel-metrics
    namespace: otel-metrics
  spec:
    mode: statefulset
    targetAllocator:
      enabled: true
      serviceAccount: opentelemetry-targetallocator-sa
      prometheusCR:
        enabled: true
    config: |-
      receivers:
        otlp:
          protocols:
            grpc: {}
            http: {}
        prometheus:
          target_allocator:
            endpoint: http://otel-metrics-targetallocator-service
            interval: 30s
            collector_id: ${POD_NAME}
      exporters:
        jaeger:
          endpoint: tracing-collector.observability.svc.cluster.local:14250
          tls:
            insecure: true
          sending_queue:
            enabled: true
          retry_on_failure:
            enabled: true
      service:
        pipelines:
          metrics:
            receivers:
            - prometheus
            exporters:
            - jaeger
          traces:
            receivers:
            - otlp
            exporters:
            - jaeger