apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    ingressGateways:
    - name: redis-ingressgateway
      enabled: true
      k8s:
        service:
          ports:
          - name: status-port
            port: 15021
            targetPort: 15021
          - name: tcp
            nodePort: 31379
            port: 31400
            targetPort: 31400
        serviceAnnotations:
          mygraph/ingressgateway: redis
    - name: mysql-ingressgateway
      enabled: true
      k8s:
        service:
          ports:
          - name: status-port
            port: 15021
            targetPort: 15021
          - name: tcp
            nodePort: 31306
            port: 31400
            targetPort: 31400
        serviceAnnotations:
          mygraph/ingressgateway: mysql
    - name: rabbitmq-ingressgateway
      enabled: true
      k8s:
        service:
          ports:
          - name: status-port
            port: 15021
            targetPort: 15021
          - name: tcp
            nodePort: 31672
            port: 31400
            targetPort: 31400
        serviceAnnotations:
          mygraph/ingressgateway: rabbitmq