apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    ingressGateways:
    - name: istio-ingressgateway
      k8s:
        service:
          ports:
          - name: tcp-redis
            nodePort: 31379
            port: 6379
            targetPort: 6379
          - name: tcp-mysql
            nodePort: 31306
            port: 3306
            targetPort: 3306
          - name: tcp-amqp
            nodePort: 31672
            port: 5672
            targetPort: 5672