# https://istio.io/latest/zh/docs/setup/additional-setup/gateway/
# https://istio.io/latest/zh/docs/tasks/observability/logs/otel-provider/
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: ingress
spec:
  profile: empty
  meshConfig:
    accessLogFile: /dev/stdout
    defaultConfig:
      gatewayTopology:
        numTrustedProxies: 5
    extensionProviders:
    - name: otel
      envoyOtelAls:
        service: otel-collector.observability.svc.cluster.local
        port: 4317
        logFormat:
          labels:
            pod: '%ENVIRONMENT(POD_NAME)%'
            namespace: '%ENVIRONMENT(POD_NAMESPACE)%'
            cluster: '%ENVIRONMENT(ISTIO_META_CLUSTER_ID)%'
            mesh: '%ENVIRONMENT(ISTIO_META_MESH_ID)%'
    defaultProviders:
      accessLogging:
      - envoy
      - otel
  components:
    ingressGateways:
    - name: istio-ingressgateway
      namespace: istio-system
      enabled: true
      label:
        istio: ingressgateway
      k8s:
        service:
          externalTrafficPolicy: Local
          ports:
          - port: 15021
            targetPort: 15021
            name: tcp-status
            protocol: TCP
          - port: 80
            targetPort: 8080
            name: http2
            protocol: TCP
          - port: 443
            targetPort: 8443
            name: https
            protocol: TCP
          - port: 6379
            targetPort: 6379
            name: tcp-redis
            protocol: TCP
          - port: 5432
            targetPort: 5432
            name: tcp-postgres
            protocol: TCP
          - port: 5672
            targetPort: 5672
            name: tcp-amqp
            protocol: TCP
  values:
    gateways:
      istio-ingressgateway:
        injectionTemplate: gateway