# https://istio.io/latest/zh/docs/reference/config/networking/gateway/
# https://istio.io/latest/zh/docs/reference/config/networking/virtual-service/
apiVersion: v1
kind: List
items:
- apiVersion: networking.istio.io/v1
  kind: Gateway
  metadata:
    name: gateway
    namespace: istio-ingress
  spec:
    selector:
      istio: ingressgateway
    servers:
    - port:
        number: 80
        protocol: HTTP
        name: http
      hosts:
      - rancher.renlm.cn
    - port:
        number: 443
        protocol: HTTPS
        name: tls
      hosts:
      - kubernetes.renlm.cn
      tls:
        mode: PASSTHROUGH
- apiVersion: networking.istio.io/v1
  kind: VirtualService
  metadata:
    name: rancher
    namespace: istio-ingress
  spec:
    hosts:
    - rancher.renlm.cn
    gateways:
    - gateway
    http:
    - match:
      - port: 80
      route:
      - destination:
          host: rancher.cattle-system.svc.cluster.local
          port:
            number: 80
- apiVersion: networking.istio.io/v1
  kind: VirtualService
  metadata:
    name: kubernetes
    namespace: istio-ingress
  spec:
    hosts:
    - kubernetes.renlm.cn
    gateways:
    - gateway
    tls:
    - match:
      - port: 443
        sniHosts:
        - kubernetes.renlm.cn
      route:
      - destination:
          host: kubernetes.default.svc.cluster.local
          port:
            number: 443