defaultVhost: /dev
defaultUser: dev
defaultPass: PWD
nodeSelector: {}
image:
  repository: rabbitmq
  pullPolicy: IfNotPresent
  tag: management
serviceAccount:
  create: false
ingress:
  enabled: true
  annotations: {}
  hosts:
  - host: rabbitmq.renlm.cn
    paths:
    - path: /
      pathType: Prefix
  tls:
  - secretName: renlm.secret
    hosts:
    - rabbitmq.renlm.cn
service:
  type: NodePort
  port: 15672
  amqpPort: 5672
  amqpNodePort: 30672