defaultVhost: /dev
defaultUser: dev
defaultPass: PWD
nodeSelector: {}
image:
  repository: rabbitmq
  pullPolicy: IfNotPresent
  tag: management
serviceAccount:
  create: false
ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: true
  hosts:
  - host: rabbitmq.renlm.cn
    paths:
    - path: /
      pathType: ImplementationSpecific
  tls:
  - secretName: renlm.secret
    hosts:
    - rabbitmq.renlm.cn
service:
  type: NodePort
  amqpPort: 5672
  amqpNodePort: 30672
  httpPort: 15672