host: &host rabbitmq.renlm.cn
tlsSecretName: &tlsSecretName renlm.secret
defaultVhost: /dev
defaultUser: dev
defaultPass: PWD
nodeSelector: {}
image:
  repository: rabbitmq
  pullPolicy: IfNotPresent
  tag: management
serviceAccount:
  create: false
ingress:
  enabled: true
  annotations: {}
  hosts:
  - host: *host
    paths:
    - path: /
      pathType: Prefix
  tls:
  - secretName: *tlsSecretName
    hosts:
    - *host
service:
  type: NodePort
  port: 15672
  amqpPort: 5672
  amqpNodePort: 30672