apiVersion: v1
kind: Service
metadata:
  name: {{ include "rabbitmq.fullname" . }}
  labels:
    {{- include "rabbitmq.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.amqpPort }}
      targetPort: amqp-tcp
      nodePort: {{ .Values.service.amqpNodePort }}
      protocol: TCP
      name: amqp-tcp
  selector:
    {{- include "rabbitmq.selectorLabels" . | nindent 4 }}
